services:
  frontend:
    image: camilg/frontend

    ports:
      - "3000:80"

  backend:
    image: camilg/django_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: a_secret_key
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: postgresql
      DB_USER: postgresql
      DB_PASS: postgresql
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgresql
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    volumes:
      - db:/var/lib/postgresql/data

volumes:
    db:
